[package]
name = "funcgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
egui = "0.31.1"
tree-sitter = "0.25.3"
tree-sitter-rust = "0.24"

[build-dependencies]
cc="*"
