java1: 
  cargo run -- -l java -d ~/funcgraph/test_files/Java.java

java2:
  cargo run -- -l java -d ~/funcgraph/test_files/Java2.java

java3:
  cargo run -- -l java -d ~/funcgraph/test_files/Java3.java

rust:
  cargo run -- -l rust -d ~/funcgraph/test_files/Rust.rs

python:
  cargo run -- -l python -d ~/funcgraph/test_files/Python.py
